{{- range $name, $service := .Values.services }}
{{- if $service.namespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $service.namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: crm
---
{{- end }}
{{- end }}
